# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  repoName: '0rtem'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-registry'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-registry'
        repository: '0rtem'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(repoName)/$(tag)
          

    - task: Docker@2
      inputs:
        containerRegistry: 'docker-registry'
        command: 'logout'